name: bienesraices
recipe: php
config:
  php: '8.3'
  via: apache
  webroot: .
services:
  appserver:
    build_as_root:
      - a2enmod rewrite
      - a2enmod headers
  database:
    portforward: true
    type: mariadb:10.5
    creds:
      user: bienesraicesdb
      password: bienesraicesdb
      database: bienesraicesdb
  pma:
    type: phpmyadmin
    hosts: database
